# Generated by Django 5.2.6 on 2025-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_file_alter_chatmessage_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
