# Generated by Django 4.2.7 on 2025-12-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_growprogoal_growproupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_projects', to='core.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='task_stakeholder', to='core.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('INTERNAL', 'Intern'), ('EXTERNAL', 'Extern')], default='EXTERNAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
    ]
