# Generated by Django 4.2.7 on 2025-12-17 21:09

from django.db import migrations, models


def copy_assignees_forward(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    for task in Task.objects.exclude(assignee__isnull=True):
        task.assignees.add(task.assignee)


def copy_assignees_backward(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    for task in Task.objects.all():
        first = task.assignees.first()
        task.assignee_id = first.id if first else None
        task.save(update_fields=["assignee"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_owners_task_stakeholders_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='core.profile'),
        ),
        migrations.RunPython(copy_assignees_forward, copy_assignees_backward),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
    ]
