# Generated by Django 4.2.7 on 2025-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_task_assignee_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
