# Generated by Django 4.2.7 on 2026-02-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='plugin_guides/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugin_guides', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
