# Generated by Django 4.2.7 on 2026-02-22 16:20

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pluginguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('api_key', models.CharField(default=core.models._generate_system_api_key, max_length=64, unique=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='growprogoal',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='growpro_assigned', to='core.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='review_status',
            field=models.CharField(blank=True, choices=[('REVIEWED', 'Reviewed'), ('NOT_REVIEWED', 'Nicht reviewed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('TASK_STATUS', 'Task Status'), ('TASK_DUE', 'Task Frist'), ('GROWPRO_DUE', 'GrowPro Frist'), ('PROJECT_STATUS', 'Projekt Status')], max_length=30)),
                ('action', models.CharField(choices=[('NOTIFY', 'Benachrichtigen'), ('ASSIGN', 'Zuweisen'), ('WEBHOOK', 'Webhook')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='core.profile')),
            ],
        ),
    ]
