# Generated by Django 4.2.7 on 2026-04-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_created_by_task_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participant_task_access',
            field=models.CharField(choices=[('NONE', 'Keine Task-Rechte'), ('COMMENT', 'Kommentare'), ('EDIT', 'Tasks bearbeiten')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_recurrences', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_pattern',
            field=models.CharField(choices=[('NONE', 'Keine'), ('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich')], default='NONE', max_length=12),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='system', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Erfolg'), ('WARNING', 'Hinweis'), ('DANGER', 'Alarm')], default='INFO', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='core.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.profile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
