# Generated by Django 4.2.7 on 2026-04-11 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_participant_task_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar'), ('CHF', 'Schweizer Franken')], default='EUR', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_savings_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('emergency_buffer_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_projects', to='core.profile')),
            ],
            options={
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('PRIMARY', 'Hauptperson'), ('PARTNER', 'Partner'), ('CHILD', 'Kind'), ('OTHER', 'Weitere Person')], default='PRIMARY', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.financeproject')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('entry_type', models.CharField(choices=[('INCOME', 'Einnahme'), ('FIXED', 'Fixkosten'), ('VARIABLE', 'Variable Ausgabe'), ('DEBT', 'Schuldenrate'), ('SAVING', 'Sparen')], default='FIXED', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monatlich'), ('WEEKLY', 'Woechentlich'), ('YEARLY', 'Jaehrlich'), ('ONCE', 'Einmalig')], default='MONTHLY', max_length=12)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.financemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.financeproject')),
            ],
            options={
                'ordering': ['entry_type', 'title', '-created_at'],
            },
        ),
    ]
