# Generated by Django 4.2.7 on 2026-04-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_financeproject_financemember_financeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Klarna, Darlehen, etc.', max_length=200)),
                ('payment_type', models.CharField(choices=[('INSTALLMENT', 'Ratenzahlung'), ('FIXED_AMOUNT', 'Fixbetrag')], default='INSTALLMENT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Gesamtbetrag der Schulden', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Bisheriger bezahlter Betrag', max_digits=12)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Monatliche Zahlungsrate', max_digits=12, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Tag im Monat fuer die Zahlungen (1-31)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktiv'), ('PAID_OFF', 'Abbezahlt'), ('PAUSED', 'Pausiert')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('paid_off_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.financeproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
