# Generated by Django 4.2.7 on 2026-04-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_debt_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeproject',
            name='savings_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prozent vom Rest zur Seite legen (0-100)', max_digits=5),
        ),
    ]
