# Generated by Django 4.2.7 on 2026-04-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_savings_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, help_text='z.B. Lebensmittel, Transport, Unterhaltung', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_expenses', to='core.financemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to='core.financeproject')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'date', 'title', 'amount')},
            },
        ),
    ]
