# Generated by Django 4.2.7 on 2026-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dailyexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_kind',
            field=models.CharField(choices=[('DEBT', 'Schuld'), ('CREDIT', 'Kredit')], default='DEBT', max_length=10),
        ),
        migrations.AddField(
            model_name='financeproject',
            name='dispo_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
