# Generated by Django 4.2.7 on 2026-04-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_debt_debt_kind_financeproject_dispo_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('tip_type', models.CharField(choices=[('CASHBACK', 'Cashback'), ('DISCOUNT', 'Rabattaktion'), ('REFERRAL', 'Empfehlungspraemie'), ('OTHER', 'Sonstiges')], default='OTHER', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_tips', to='core.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
