# Generated by Django 4.2.7 on 2026-04-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_financetip'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeproject',
            name='dispo_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
