# Generated by Django 4.2.7 on 2026-05-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_pluginguideimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("has_application_phase", models.BooleanField(default=True)),
                ("application_deadline", models.DateTimeField(blank=True, null=True)),
                ("submission_deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Entwurf"),
                            ("APPLICATION_OPEN", "Bewerbung offen"),
                            ("SUBMISSION_OPEN", "Einreichung offen"),
                            ("BATTLES", "Battles laufen"),
                            ("CLOSED", "Geschlossen"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("require_phone_vote_verification", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="created_tournaments", to="core.profile"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TournamentSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("media_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Eingereicht"), ("APPROVED", "Freigegeben"), ("REJECTED", "Abgelehnt")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tournament_submissions", to="core.profile"),
                ),
                (
                    "tournament",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="core.tournament"),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TournamentBattle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.PositiveIntegerField(default=1)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SCHEDULED", "Geplant"), ("LIVE", "Live"), ("CLOSED", "Abgeschlossen")],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "left_submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="battles_as_left", to="core.tournamentsubmission"),
                ),
                (
                    "right_submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="battles_as_right", to="core.tournamentsubmission"),
                ),
                (
                    "tournament",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="battles", to="core.tournament"),
                ),
            ],
            options={"ordering": ["-round_number", "-created_at"]},
        ),
        migrations.CreateModel(
            name="TournamentApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Offen"), ("APPROVED", "Bestätigt"), ("REJECTED", "Abgelehnt")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_tournament_applications", to="core.profile"),
                ),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tournament_applications", to="core.profile"),
                ),
                (
                    "tournament",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="core.tournament"),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("tournament", "profile")}},
        ),
        migrations.CreateModel(
            name="TournamentVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("NONE", "Nicht erforderlich"), ("PENDING_PHONE", "Telefonnummer offen"), ("VERIFIED", "Telefonnummer verifiziert")],
                        default="NONE",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "battle",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.tournamentbattle"),
                ),
                (
                    "selected_submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="core.tournamentsubmission"),
                ),
                (
                    "voter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tournament_votes", to="core.profile"),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("battle", "voter")}},
        ),
    ]
