# Generated by Django 4.2.7 on 2026-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_tournamentbattle_winner_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedSeasonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveSmallIntegerField(default=3)),
                ('seasons_per_year', models.PositiveSmallIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ranked Season Settings',
            },
        ),
        migrations.CreateModel(
            name='RankTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_key', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILBER', 'Silber'), ('GOLD', 'Gold'), ('PLATIN', 'Platin'), ('RUBIN', 'Rubin')], max_length=16, unique=True)),
                ('display_name', models.CharField(max_length=32)),
                ('accent', models.CharField(default='#9a6b42', max_length=16)),
                ('min_points', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(blank=True, null=True)),
                ('win_points', models.PositiveIntegerField(default=140)),
                ('vote_points', models.PositiveIntegerField(default=2)),
                ('submission_points', models.PositiveIntegerField(default=32)),
                ('battle_points', models.PositiveIntegerField(default=10)),
                ('loss_penalty', models.PositiveIntegerField(default=15)),
                ('max_losses_without_penalty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['min_points', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_no_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='next_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='recurrence_interval',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'Keine'), ('WEEKLY', 'Woechentlich'), ('MONTHLY', 'Monatlich'), ('QUARTERLY', 'Quartalsweise')], default='NONE', max_length=12),
        ),
        migrations.AddField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
