# Generated by Django 4.2.7 on 2026-06-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_financesavingsgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PAYMENT_CREATED', 'Payment created'), ('PAYMENT_UPDATED', 'Payment updated'), ('PAYMENT_DELETED', 'Payment deleted'), ('PAYMENT_SKIPPED', 'Payment skipped'), ('PAYMENT_MISSED', 'Payment missed'), ('MANUAL_OVERRIDE', 'Manual override')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('is_undone', models.BooleanField(default=False)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_audit_logs', to='core.profile')),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.debt')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.debtpayment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.financeproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
