# Generated by Django 4.2.7 on 2026-06-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_financeauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('MILESTONE', 'Meilenstein'), ('BADGE', 'Abzeichen'), ('SPECIAL', 'Spezial'), ('SEASONAL', 'Saisonal')], default='BADGE', max_length=12)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG content für Icon')),
                ('icon_color', models.CharField(default='#FFD700', max_length=7)),
                ('is_hidden', models.BooleanField(default=False)),
                ('rarity', models.CharField(choices=[('COMMON', 'Häufig'), ('RARE', 'Selten'), ('EPIC', 'Episch'), ('LEGENDARY', 'Legendär')], default='COMMON', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='ranktierconfig',
            name='tier_key',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILBER', 'Silber'), ('GOLD', 'Gold'), ('PLATIN', 'Platin'), ('LEGENDAER', 'Legendär')], max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='ProfileAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='core.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.profile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('profile', 'achievement')},
            },
        ),
    ]
