# Generated by Django 4.2.7 on 2026-06-21 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_achievement_alter_ranktierconfig_tier_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='songs/covers/'),
        ),
        migrations.AddField(
            model_name='songversion',
            name='version_type',
            field=models.CharField(choices=[('BEAT', 'Beat'), ('DEMO', 'Demo'), ('DRAFT', 'Draft'), ('ACOUSTIC', 'Acoustic'), ('INSTRUMENTAL', 'Instrumental'), ('MIX', 'Mix'), ('MASTER', 'Master'), ('FINAL', 'Final')], default='DEMO', max_length=16),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='songs/album_covers/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='core.profile')),
                ('songs', models.ManyToManyField(blank=True, related_name='albums', to='core.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
